// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGBu8mWMFcurAcXqYO-sYwqWOXXCqqMA8',
    appId: '1:938735929616:android:f9f89907ee531931623d95',
    messagingSenderId: '938735929616',
    projectId: 'likhbee',
    storageBucket: 'likhbee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxRvGj9tQNXE5HTXtnxO38TKculb-99U',
    appId: '1:938735929616:ios:9670e57211f5c9cf623d95',
    messagingSenderId: '938735929616',
    projectId: 'likhbee',
    storageBucket: 'likhbee.appspot.com',
    androidClientId: '938735929616-qcufmk3u099u3hpgaq64a94qqt25mokg.apps.googleusercontent.com',
    iosClientId: '938735929616-8mkm7flmbbimajg2cjb0heuap4gog716.apps.googleusercontent.com',
    iosBundleId: 'com.inertia.likhBee',
  );
}
